import manifest from './manifest.json'

/**
 * The catalogue of character parts, and the rules for a valid character.
 *
 * `manifest.json` is generated by `scripts/characters/process_all.py` — every
 * number in it is a measurement of the finished artwork, so nothing here is
 * hand-maintained and nothing drifts when a part is regenerated.
 */

export const SLOTS = ['head', 'body', 'arm', 'leg'] as const
export type Slot = (typeof SLOTS)[number]

export interface Part {
  id: string
  w: number
  h: number
  /** Where this part hangs from, in its own pixels. See ADR-0033. */
  pivot: [number, number]
}

export type Character = Record<Slot, string>

/** Human-readable slot names, for the picker. Plural where you get two. */
export const SLOT_LABELS: Record<Slot, string> = {
  head: 'Head',
  body: 'Body',
  arm: 'Arms',
  leg: 'Legs',
}

export type RigPoint = 'neck' | 'chin' | 'shoulderL' | 'shoulderR' | 'hipL' | 'hipR'

/**
 * Everything below is asserted through `unknown`.
 *
 * A JSON import widens `[260, 202]` to `number[]`, which will not narrow to a
 * pair however it is annotated. The generator is the guarantee instead: every
 * coordinate it writes is a measurement of the finished artwork, and the
 * manifest test asserts the shape so a malformed one fails the build rather
 * than the browser.
 */
export const FRAME = manifest.frame as unknown as readonly [number, number]

export const RIG = manifest.rig as unknown as Record<RigPoint, [number, number]>

const CATALOGUE = manifest.slots as unknown as Record<Slot, Part[]>

export function partsIn(slot: Slot): Part[] {
  return CATALOGUE[slot]
}

export function findPart(slot: Slot, id: string): Part | null {
  return CATALOGUE[slot].find((part) => part.id === id) ?? null
}

/** Where the browser fetches a part from. Thumbnails are a tenth the weight. */
export function partUrl(slot: Slot, id: string, variant: 'full' | 'thumb' = 'full'): string {
  return `/characters/${slot}/${id}${variant === 'thumb' ? '.thumb' : ''}.webp`
}

/**
 * A complete character, picked at random.
 *
 * Sign-up opens on one of these rather than on an empty figure. An empty
 * outline asks somebody to build a person from nothing; a finished stranger
 * asks them to change the bits they do not like, which is a much easier
 * question and gets people through the screen.
 */
export function randomCharacter(): Character {
  const pick = (slot: Slot): string => {
    const parts = CATALOGUE[slot]
    const choice = parts[Math.floor(Math.random() * parts.length)]
    // Only reachable if a slot is empty, which would mean a broken manifest.
    if (!choice) throw new Error(`No parts available for slot "${slot}"`)
    return choice.id
  }

  return { head: pick('head'), body: pick('body'), arm: pick('arm'), leg: pick('leg') }
}

/**
 * Pull every part into the browser cache, ahead of anybody clicking anything.
 *
 * Without this the first click on a thumbnail fetches that part's full-size
 * image, so the figure changes a beat *after* the click — which reads as the
 * app being slow rather than as an image loading. The whole catalogue is under
 * a megabyte, so the honest fix is to have all of it before it is needed.
 *
 * Runs once per page: the browser cache does the real work, and the promise is
 * kept so a second caller waits on the first rather than starting again.
 */
let preloading: Promise<void> | null = null

export function preloadParts(): Promise<void> {
  if (preloading) return preloading

  preloading = Promise.all(
    SLOTS.flatMap((slot) =>
      CATALOGUE[slot].map(
        (part) =>
          new Promise<void>((resolve) => {
            const image = new Image()
            // Resolve either way. A part that fails to load is a broken picture
            // later, not a reason to leave the picker waiting for ever.
            image.onload = () => resolve()
            image.onerror = () => resolve()
            image.src = partUrl(slot, part.id)
          }),
      ),
    ),
  ).then(() => undefined)

  return preloading
}

/**
 * Whether something read back from storage is still a character we can render.
 *
 * Worth checking rather than trusting: these come out of Clerk's
 * `unsafeMetadata`, which is client-writable, and out of localStorage in
 * development. Either can hold an id from a catalogue that has since changed.
 */
export function isCharacter(value: unknown): value is Character {
  if (typeof value !== 'object' || value === null) return false
  const candidate = value as Record<string, unknown>
  return SLOTS.every((slot) => {
    const id = candidate[slot]
    return typeof id === 'string' && findPart(slot, id) !== null
  })
}
